import { BreakpointsOptions } from './styles.interface';
export declare const DEFAULT_FONT_FAMILY = "BlinkMacSystemFont, -apple-system, Segoe UI, Roboto, Oxygen-Sans, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, Helvetica, Arial, sans-serif";
export declare const DEFAULT_FONT_SIZE = 14;
export declare const DEFAULT_LIGHT_THEME_ACCENT_COLOR = "hsl(214.9, 100%, 32.4%)";
export declare const DEFAULT_LIGHT_THEME_FONT_COLOR = "hsl(0.0, 0%, 19%)";
export declare const DEFAULT_LIGHT_THEME_NEUTRAL_COLOR = "hsl(0.0, 0%, 96.0%)";
export declare const UC_WHITE = "#ffffff";
export declare const UC_BLUE = "#0045A5";
export declare const FONT_WEIGHT_LIGHT = 250;
export declare const FONT_WEIGHT_REGULAR = 400;
export declare const FONT_WEIGHT_SEMI_BOLD = 550;
export declare const FONT_WEIGHT_BOLD = 700;
export declare const DEFAULT_MAX_SIDE_AND_CENTER_CONTAINER_WIDTH = 625;
export declare const DEFAULT_MAX_BANNER_WIDTH = 5000;
export declare const DEFAULT_BORDER_RADIUS = "4px";
export declare const DEFAULT_LAYER_BORDER_RADIUS = "8px";
export declare const DEFAULT_LAYER_COLOR = "#ffffff";
export declare const DEFAULT_OVERLAY_COLOR = "#333";
export declare const DEFAULT_OVERLAY_OPACITY = 0.7;
export declare const DEFAULT_ACTIVE_TOGGLE = "#336AB7";
export declare const DEFAULT_DISABLED_TOGGLE = "#dedede";
export declare const DEFAULT_INACTIVE_TOGGLE = "#595959";
export declare const DEFAULT_TOGGLE_ICON = "#ffffff";
export declare const PRIVACY_BUTTON_DESKTOP_SIZE = 64;
export declare const PRIVACY_BUTTON_MOBILE_SIZE = 44;
export declare const breakpoints: BreakpointsOptions;
